stages:
  load_data:
    cmd : python src/load_data.py --config=params.yaml
    deps : 
    - src/get_data.py
    - src/load_data.py
    - data_given/laptop_data.csv
    outs:
    - data/raw/laptop_data.csv
  
  split_data:
    cmd : python src/split_data.py --config=params.yaml
    deps : 
    - src/split_data.py
    - data/raw/laptop_data.csv
    outs :
    - data/processed/train_laptop_data.csv
    - data/processed/test_laptop_data.csv
  
  train_and_evaluate:
    cmd : python src/train_and_evaluate.py --config=params.yaml

    deps : 
    - data/processed/train_laptop_data.csv
    - data/processed/test_laptop_data.csv
    - src/train_and_evaluate.py

    params:
    - estimators.RandomForestRegressor.params.n_estimators
    - estimators.RandomForestRegressor.params.max_depth
    - estimators.RandomForestRegressor.params.max_features
    - estimators.RandomForestRegressor.params.random_state
    - estimators.RandomForestRegressor.params.max_samples

    metrics : 
    - report/scores.json:
       cache: false
    - report/params.json:
       cache: false
    outs:
    - saved_models/model.joblib
    



