base:
  project : laptop_price_prediction
  random_state : 42
  target_col : Price

data_source:
  s3_source : data_given/laptop_data.csv

load_data:
  raw_dataset_csv : data/raw/laptop_data.csv

split_data:
  train_path : data/processed/train_laptop_data.csv
  test_path : data/processed/test_laptop_data.csv
  test_size : 0.15

estimators : 
 RandomForestRegressor:
   params:
       #n_estimators : 100
       #random_state : 3
       #max_samples : 0.5
       #max_features : 0.075
       #max_depth : 15
       n_estimators : 90
       random_state : 4
       max_samples : 0.3
       max_features : 0.075
       max_depth : 10
model_dir : saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib




  
